[package]
name = "rkhd"
version = "0.1.0"
authors = ["Giancarlo Palavicini <kasthor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.12"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
